# Generated by Django 4.0.4 on 2022-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_2', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_3', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_4', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_5', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_6', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_7', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_8', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_9', models.IntegerField(verbose_name='Ваш ответ')),
                ('answer_10', models.IntegerField(verbose_name='Ваш ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='отчество')),
                ('mail', models.EmailField(max_length=50, verbose_name='почта')),
                ('school', models.CharField(max_length=30, verbose_name='школа')),
                ('number', models.CharField(choices=[('5', 'пятый'), ('6', 'шестой'), ('7', 'седьмой'), ('8', 'восьмой'), ('9', 'девятый'), ('10', 'десятый'), ('11', 'одиннадцатый')], max_length=300)),
                ('letter', models.CharField(choices=[('1', 'А'), ('2', 'Б'), ('3', 'В'), ('4', 'Г'), ('5', 'Д'), ('6', 'Е'), ('7', 'Ё')], max_length=300)),
                ('certificate', models.BooleanField()),
                ('password', models.CharField(max_length=50, verbose_name='пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Условие задачи')),
                ('task', models.TextField(verbose_name='Ответ задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
